version: '3.8'
services:
  db:
    image: postgres
    container_name: campanha-manager-db-1
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5500:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
